(*
Steps to recreate
- Open this EBNF file
- Press ctrl+/ (or cmd+/ on macOS)

Current behavior
Adds C-style line comment // ... to the beginning of the line

Expected behavior
Ideally it should add (* ... *) style comment to the line

---
Note: 
ebnf.configuration.json defines single line comment.
Block comment doesnt function properly.
*)

program
    = { item };

item
    = fn_defn
    | fn_decl;

fn_defn
    = "typed-ident";

param_list
    = "void"
    | { typed_ident, "," }, typed_ident;